package org.monitoring.catchholebackend.domain.aitoken.type;

public enum AiTokenPurpose {
    SETTING_EXTRACTION,
    SUBJECT_RESOLUTION,
    CHUNK_EMBEDDING,
    WORLD_SETTING_EXTRACTION,
    WORLD_SETTING_SUBJECT_RESOLUTION,
    WORLD_SETTING_COMPARISON,
    CHARACTER_FACT_COMPARISON
}
