CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    phone_verified BOOLEAN NOT NULL,
    display_name VARCHAR(50) NOT NULL,
    profile_image_url VARCHAR(2048),
    status VARCHAR(30) NOT NULL,
    role VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_members_email UNIQUE (email),
    CONSTRAINT uk_members_phone_number UNIQUE (phone_number)
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_member
        FOREIGN KEY (member_id) REFERENCES members (id)
);

CREATE TABLE works (
    id UUID PRIMARY KEY,
    member_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    genre VARCHAR(50),
    description TEXT,
    latest_episode_no INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_works_member
        FOREIGN KEY (member_id) REFERENCES members (id)
);

CREATE TABLE upload_batches (
    id UUID PRIMARY KEY,
    work_id UUID NOT NULL,
    member_id BIGINT NOT NULL,
    upload_type VARCHAR(40) NOT NULL,
    source_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    file_count INTEGER NOT NULL,
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_upload_batches_work
        FOREIGN KEY (work_id) REFERENCES works (id),
    CONSTRAINT fk_upload_batches_member
        FOREIGN KEY (member_id) REFERENCES members (id)
);

CREATE TABLE upload_files (
    id UUID PRIMARY KEY,
    batch_id UUID NOT NULL,
    file_role VARCHAR(30) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    mime_type VARCHAR(100),
    storage_url VARCHAR(512),
    file_size BIGINT NOT NULL,
    detected_episode_start_no INTEGER,
    detected_episode_end_no INTEGER,
    detected_episode_count INTEGER,
    parse_status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_upload_files_batch
        FOREIGN KEY (batch_id) REFERENCES upload_batches (id)
);

CREATE TABLE episodes (
    id UUID PRIMARY KEY,
    work_id UUID NOT NULL,
    source_file_id UUID,
    episode_no INTEGER NOT NULL,
    title VARCHAR(100),
    content_s3_key VARCHAR(512),
    content_s3_version VARCHAR(100),
    content_hash VARCHAR(64),
    char_count INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_episodes_work
        FOREIGN KEY (work_id) REFERENCES works (id),
    CONSTRAINT fk_episodes_source_file
        FOREIGN KEY (source_file_id) REFERENCES upload_files (id)
);

CREATE TABLE analysis_jobs (
    id UUID PRIMARY KEY,
    work_id UUID NOT NULL,
    batch_id UUID,
    episode_id UUID,
    job_type VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL,
    current_step VARCHAR(100),
    model_name VARCHAR(100),
    input_token_count INTEGER,
    output_token_count INTEGER,
    summary_json TEXT,
    error_message TEXT,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_analysis_jobs_work
        FOREIGN KEY (work_id) REFERENCES works (id),
    CONSTRAINT fk_analysis_jobs_upload_batch
        FOREIGN KEY (batch_id) REFERENCES upload_batches (id),
    CONSTRAINT fk_analysis_jobs_episode
        FOREIGN KEY (episode_id) REFERENCES episodes (id)
);

CREATE TABLE characters (
    id UUID PRIMARY KEY,
    work_id UUID NOT NULL,
    name VARCHAR(100) NOT NULL,
    role_label VARCHAR(50),
    current_age INTEGER,
    current_level INTEGER,
    profile_json JSONB,
    stats_json JSONB,
    skills_json JSONB,
    items_json JSONB,
    statuses_json JSONB,
    first_appearance_episode_id UUID,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_characters_work
        FOREIGN KEY (work_id) REFERENCES works (id)
);

CREATE INDEX idx_characters_work_name
    ON characters (work_id, name);
CREATE INDEX idx_characters_work_status
    ON characters (work_id, status);

CREATE TABLE episode_chunks (
    id UUID PRIMARY KEY,
    episode_id UUID NOT NULL,
    chunk_index INTEGER NOT NULL,
    chunk_text TEXT NOT NULL,
    start_offset INTEGER NOT NULL,
    end_offset INTEGER NOT NULL,
    paragraph_start_index INTEGER NOT NULL,
    paragraph_end_index INTEGER NOT NULL,
    metadata_json JSONB,
    embedding VECTOR(1536),
    embedding_model VARCHAR(100),
    embedding_version VARCHAR(50),
    embedded_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_episode_chunks_episode_index
        UNIQUE (episode_id, chunk_index),
    CONSTRAINT fk_episode_chunks_episode
        FOREIGN KEY (episode_id) REFERENCES episodes (id) ON DELETE CASCADE
);

CREATE INDEX idx_episode_chunks_episode_id
    ON episode_chunks (episode_id);
CREATE INDEX idx_episode_chunks_embedding_cosine
    ON episode_chunks USING hnsw (embedding vector_cosine_ops);

CREATE TABLE setting_candidates (
    id UUID PRIMARY KEY,
    work_id UUID NOT NULL,
    episode_id UUID,
    source_chunk_id UUID,
    analysis_job_id UUID,
    entity_type VARCHAR(30) NOT NULL,
    entity_name VARCHAR(100) NOT NULL,
    raw_entity_mention VARCHAR(100),
    matched_character_id UUID,
    match_status VARCHAR(30) NOT NULL,
    attribute_name VARCHAR(100) NOT NULL,
    attribute_value TEXT,
    value_type VARCHAR(30) NOT NULL,
    value_json JSONB,
    evidence_spans JSONB,
    confidence NUMERIC(5, 4),
    review_status VARCHAR(30) NOT NULL,
    raw_ai_result_json JSONB,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_setting_candidates_work
        FOREIGN KEY (work_id) REFERENCES works (id),
    CONSTRAINT fk_setting_candidates_episode
        FOREIGN KEY (episode_id) REFERENCES episodes (id),
    CONSTRAINT fk_setting_candidates_analysis_job
        FOREIGN KEY (analysis_job_id) REFERENCES analysis_jobs (id),
    CONSTRAINT fk_setting_candidates_matched_character
        FOREIGN KEY (matched_character_id) REFERENCES characters (id)
);

CREATE INDEX idx_setting_candidates_work_entity_review
    ON setting_candidates (work_id, entity_name, review_status);
CREATE INDEX idx_setting_candidates_work_attribute
    ON setting_candidates (work_id, attribute_name);

CREATE TABLE character_facts (
    id UUID PRIMARY KEY,
    character_id UUID NOT NULL,
    fact_type VARCHAR(30) NOT NULL,
    fact_key VARCHAR(150) NOT NULL,
    fact_value TEXT,
    normalized_value TEXT,
    value_json JSONB,
    source_episode_id UUID,
    source_chunk_id UUID,
    extracted_by_job_id UUID,
    confidence NUMERIC(5, 4),
    is_current BOOLEAN NOT NULL,
    effective_from_episode_no INTEGER,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_character_facts_character
        FOREIGN KEY (character_id) REFERENCES characters (id),
    CONSTRAINT fk_character_facts_source_episode
        FOREIGN KEY (source_episode_id) REFERENCES episodes (id),
    CONSTRAINT fk_character_facts_analysis_job
        FOREIGN KEY (extracted_by_job_id) REFERENCES analysis_jobs (id)
);

CREATE INDEX idx_character_facts_character_current
    ON character_facts (character_id, is_current);
CREATE INDEX idx_character_facts_character_key
    ON character_facts (character_id, fact_type, fact_key);
CREATE INDEX idx_character_facts_source_episode
    ON character_facts (source_episode_id);
CREATE INDEX idx_character_facts_job
    ON character_facts (extracted_by_job_id);
