CREATE TABLE member_legal_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    document_type VARCHAR(40) NOT NULL,
    document_version VARCHAR(50) NOT NULL,
    action_type VARCHAR(30) NOT NULL,
    recorded_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_member_legal_records_document_version
        UNIQUE (member_id, document_type, document_version),
    CONSTRAINT fk_member_legal_records_member
        FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE CASCADE,
    CONSTRAINT ck_member_legal_records_document_type
        CHECK (document_type IN ('TERMS_OF_SERVICE', 'PRIVACY_POLICY')),
    CONSTRAINT ck_member_legal_records_action_type
        CHECK (action_type IN ('AGREED', 'ACKNOWLEDGED')),
    CONSTRAINT ck_member_legal_records_document_action
        CHECK (
            (document_type = 'TERMS_OF_SERVICE' AND action_type = 'AGREED')
            OR (document_type = 'PRIVACY_POLICY' AND action_type = 'ACKNOWLEDGED')
        )
);

CREATE INDEX idx_member_legal_records_member_recorded
    ON member_legal_records (member_id, recorded_at);
