package org.monitoring.catchholebackend.domain.worldsetting.type;

/** 세계관 비교 완료 요청이 Backend 계약을 위반한 안전한 분기 코드다. */
public enum WorldSettingComparisonValidationReason {
    CONTEXT_TARGET_DUPLICATED,
    CONTEXT_TARGET_NOT_FOUND,
    CONTEXT_VERSION_DUPLICATED,
    EXACT_TARGET_NOT_IN_CONTEXT,
    SELECTED_TARGET_NOT_IN_CONTEXT,
    REVIEW_REASON_FORBIDDEN,
    MATCHED_TARGET_REQUIRED,
    PROPOSED_PATH_MISMATCH,
    ADD_MATCHED_PATH_FORBIDDEN,
    SCOPE_REVIEW_REQUIRED,
    PROPOSED_PATH_CONFLICT,
    EXCLUDE_MATCHED_PATH_INVALID,
    EXCLUDE_MATCHED_SCOPE_WITHOUT_PROPERTY,
    SCOPE_REVIEW_REASON_INVALID,
    SCOPE_REVIEW_TARGET_REQUIRED,
    SCOPE_REVIEW_CANDIDATE_ALREADY_SCOPED,
    SCOPE_REVIEW_MATCHED_PATH_REQUIRED,
    SCOPE_REVIEW_ROOT_PATH_EXISTS,
    SCOPE_REVIEW_MATCHED_PATH_INVALID
}
